
package com.tooltwist.bsg.clientnz;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MarketCompareService", targetNamespace = "http://rpdata.com/bsg/schemas")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MarketCompareService {


    /**
     * 
     * @param getMarketComparePropertySummaryListRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetMarketComparePropertySummaryListResponse>
     */
    @WebMethod(operationName = "getMarketComparePropertySummaryList")
    public Response<GetMarketComparePropertySummaryListResponse> getMarketComparePropertySummaryListAsync(
        @WebParam(name = "getMarketComparePropertySummaryListRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getMarketComparePropertySummaryListRequest")
        GetMarketComparePropertySummaryListRequest getMarketComparePropertySummaryListRequest);

    /**
     * 
     * @param getMarketComparePropertySummaryListRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getMarketComparePropertySummaryList")
    public Future<?> getMarketComparePropertySummaryListAsync(
        @WebParam(name = "getMarketComparePropertySummaryListRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getMarketComparePropertySummaryListRequest")
        GetMarketComparePropertySummaryListRequest getMarketComparePropertySummaryListRequest,
        @WebParam(name = "getMarketComparePropertySummaryListResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetMarketComparePropertySummaryListResponse> asyncHandler);

    /**
     * 
     * @param getMarketComparePropertySummaryListRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetMarketComparePropertySummaryListResponse
     */
    @WebMethod
    @WebResult(name = "getMarketComparePropertySummaryListResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getMarketComparePropertySummaryListResponse")
    public GetMarketComparePropertySummaryListResponse getMarketComparePropertySummaryList(
        @WebParam(name = "getMarketComparePropertySummaryListRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getMarketComparePropertySummaryListRequest")
        GetMarketComparePropertySummaryListRequest getMarketComparePropertySummaryListRequest);

    /**
     * 
     * @param refineMarketComparePropertiesRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.RefineMarketComparePropertiesResponse>
     */
    @WebMethod(operationName = "refineMarketCompareProperties")
    public Response<RefineMarketComparePropertiesResponse> refineMarketComparePropertiesAsync(
        @WebParam(name = "refineMarketComparePropertiesRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "refineMarketComparePropertiesRequest")
        RefineMarketComparePropertiesRequest refineMarketComparePropertiesRequest);

    /**
     * 
     * @param asyncHandler
     * @param refineMarketComparePropertiesRequest
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "refineMarketCompareProperties")
    public Future<?> refineMarketComparePropertiesAsync(
        @WebParam(name = "refineMarketComparePropertiesRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "refineMarketComparePropertiesRequest")
        RefineMarketComparePropertiesRequest refineMarketComparePropertiesRequest,
        @WebParam(name = "refineMarketComparePropertiesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<RefineMarketComparePropertiesResponse> asyncHandler);

    /**
     * 
     * @param refineMarketComparePropertiesRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.RefineMarketComparePropertiesResponse
     */
    @WebMethod
    @WebResult(name = "refineMarketComparePropertiesResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "refineMarketComparePropertiesResponse")
    public RefineMarketComparePropertiesResponse refineMarketCompareProperties(
        @WebParam(name = "refineMarketComparePropertiesRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "refineMarketComparePropertiesRequest")
        RefineMarketComparePropertiesRequest refineMarketComparePropertiesRequest);

}
