
package com.tooltwist.bsg.clientnz;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PropertyService", targetNamespace = "http://rpdata.com/bsg/schemas")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PropertyService {


    /**
     * 
     * @param getStreetListRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetStreetListResponse>
     */
    @WebMethod(operationName = "getStreetList")
    public Response<GetStreetListResponse> getStreetListAsync(
        @WebParam(name = "getStreetListRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getStreetListRequest")
        GetStreetListRequest getStreetListRequest);

    /**
     * 
     * @param getStreetListRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getStreetList")
    public Future<?> getStreetListAsync(
        @WebParam(name = "getStreetListRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getStreetListRequest")
        GetStreetListRequest getStreetListRequest,
        @WebParam(name = "getStreetListResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetStreetListResponse> asyncHandler);

    /**
     * 
     * @param getStreetListRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetStreetListResponse
     */
    @WebMethod
    @WebResult(name = "getStreetListResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getStreetListResponse")
    public GetStreetListResponse getStreetList(
        @WebParam(name = "getStreetListRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getStreetListRequest")
        GetStreetListRequest getStreetListRequest);

    /**
     * 
     * @param getPropertySummaryListByNameSuburbRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetPropertySummaryListByNameSuburbResponse>
     */
    @WebMethod(operationName = "getPropertySummaryListByNameSuburb")
    public Response<GetPropertySummaryListByNameSuburbResponse> getPropertySummaryListByNameSuburbAsync(
        @WebParam(name = "getPropertySummaryListByNameSuburbRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertySummaryListByNameSuburbRequest")
        GetPropertySummaryListByNameSuburbRequest getPropertySummaryListByNameSuburbRequest);

    /**
     * 
     * @param getPropertySummaryListByNameSuburbRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getPropertySummaryListByNameSuburb")
    public Future<?> getPropertySummaryListByNameSuburbAsync(
        @WebParam(name = "getPropertySummaryListByNameSuburbRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertySummaryListByNameSuburbRequest")
        GetPropertySummaryListByNameSuburbRequest getPropertySummaryListByNameSuburbRequest,
        @WebParam(name = "getPropertySummaryListByNameSuburbResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetPropertySummaryListByNameSuburbResponse> asyncHandler);

    /**
     * 
     * @param getPropertySummaryListByNameSuburbRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetPropertySummaryListByNameSuburbResponse
     */
    @WebMethod
    @WebResult(name = "getPropertySummaryListByNameSuburbResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertySummaryListByNameSuburbResponse")
    public GetPropertySummaryListByNameSuburbResponse getPropertySummaryListByNameSuburb(
        @WebParam(name = "getPropertySummaryListByNameSuburbRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertySummaryListByNameSuburbRequest")
        GetPropertySummaryListByNameSuburbRequest getPropertySummaryListByNameSuburbRequest);

    /**
     * 
     * @param getPropertyIdsBySurveyPlanRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetPropertyIdsBySurveyPlanResponse>
     */
    @WebMethod(operationName = "getPropertyIdsBySurveyPlan")
    public Response<GetPropertyIdsBySurveyPlanResponse> getPropertyIdsBySurveyPlanAsync(
        @WebParam(name = "getPropertyIdsBySurveyPlanRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsBySurveyPlanRequest")
        GetPropertyIdsBySurveyPlanRequest getPropertyIdsBySurveyPlanRequest);

    /**
     * 
     * @param getPropertyIdsBySurveyPlanRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getPropertyIdsBySurveyPlan")
    public Future<?> getPropertyIdsBySurveyPlanAsync(
        @WebParam(name = "getPropertyIdsBySurveyPlanRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsBySurveyPlanRequest")
        GetPropertyIdsBySurveyPlanRequest getPropertyIdsBySurveyPlanRequest,
        @WebParam(name = "getPropertyIdsBySurveyPlanResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetPropertyIdsBySurveyPlanResponse> asyncHandler);

    /**
     * 
     * @param getPropertyIdsBySurveyPlanRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetPropertyIdsBySurveyPlanResponse
     */
    @WebMethod
    @WebResult(name = "getPropertyIdsBySurveyPlanResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsBySurveyPlanResponse")
    public GetPropertyIdsBySurveyPlanResponse getPropertyIdsBySurveyPlan(
        @WebParam(name = "getPropertyIdsBySurveyPlanRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsBySurveyPlanRequest")
        GetPropertyIdsBySurveyPlanRequest getPropertyIdsBySurveyPlanRequest);

    /**
     * 
     * @param getPropertyProfileReportRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetPropertyProfileReportResponse>
     */
    @WebMethod(operationName = "getPropertyProfileReport")
    public Response<GetPropertyProfileReportResponse> getPropertyProfileReportAsync(
        @WebParam(name = "getPropertyProfileReportRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyProfileReportRequest")
        GetPropertyProfileReportRequest getPropertyProfileReportRequest);

    /**
     * 
     * @param getPropertyProfileReportRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getPropertyProfileReport")
    public Future<?> getPropertyProfileReportAsync(
        @WebParam(name = "getPropertyProfileReportRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyProfileReportRequest")
        GetPropertyProfileReportRequest getPropertyProfileReportRequest,
        @WebParam(name = "getPropertyProfileReportResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetPropertyProfileReportResponse> asyncHandler);

    /**
     * 
     * @param getPropertyProfileReportRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetPropertyProfileReportResponse
     */
    @WebMethod
    @WebResult(name = "getPropertyProfileReportResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyProfileReportResponse")
    public GetPropertyProfileReportResponse getPropertyProfileReport(
        @WebParam(name = "getPropertyProfileReportRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyProfileReportRequest")
        GetPropertyProfileReportRequest getPropertyProfileReportRequest);

    /**
     * 
     * @param getPropertyIdFromEPReferenceRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetPropertyIdFromEPReferenceResponse>
     */
    @WebMethod(operationName = "getPropertyIdFromEPReference")
    public Response<GetPropertyIdFromEPReferenceResponse> getPropertyIdFromEPReferenceAsync(
        @WebParam(name = "getPropertyIdFromEPReferenceRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdFromEPReferenceRequest")
        GetPropertyIdFromEPReferenceRequest getPropertyIdFromEPReferenceRequest);

    /**
     * 
     * @param getPropertyIdFromEPReferenceRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getPropertyIdFromEPReference")
    public Future<?> getPropertyIdFromEPReferenceAsync(
        @WebParam(name = "getPropertyIdFromEPReferenceRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdFromEPReferenceRequest")
        GetPropertyIdFromEPReferenceRequest getPropertyIdFromEPReferenceRequest,
        @WebParam(name = "getPropertyIdFromEPReferenceResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetPropertyIdFromEPReferenceResponse> asyncHandler);

    /**
     * 
     * @param getPropertyIdFromEPReferenceRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetPropertyIdFromEPReferenceResponse
     */
    @WebMethod
    @WebResult(name = "getPropertyIdFromEPReferenceResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdFromEPReferenceResponse")
    public GetPropertyIdFromEPReferenceResponse getPropertyIdFromEPReference(
        @WebParam(name = "getPropertyIdFromEPReferenceRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdFromEPReferenceRequest")
        GetPropertyIdFromEPReferenceRequest getPropertyIdFromEPReferenceRequest);

    /**
     * 
     * @param getPropertyIdsByRadiusRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetPropertyIdsByRadiusResponse>
     */
    @WebMethod(operationName = "getPropertyIdsByRadius")
    public Response<GetPropertyIdsByRadiusResponse> getPropertyIdsByRadiusAsync(
        @WebParam(name = "getPropertyIdsByRadiusRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsByRadiusRequest")
        GetPropertyIdsByRadiusRequest getPropertyIdsByRadiusRequest);

    /**
     * 
     * @param getPropertyIdsByRadiusRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getPropertyIdsByRadius")
    public Future<?> getPropertyIdsByRadiusAsync(
        @WebParam(name = "getPropertyIdsByRadiusRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsByRadiusRequest")
        GetPropertyIdsByRadiusRequest getPropertyIdsByRadiusRequest,
        @WebParam(name = "getPropertyIdsByRadiusResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetPropertyIdsByRadiusResponse> asyncHandler);

    /**
     * 
     * @param getPropertyIdsByRadiusRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetPropertyIdsByRadiusResponse
     */
    @WebMethod
    @WebResult(name = "getPropertyIdsByRadiusResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsByRadiusResponse")
    public GetPropertyIdsByRadiusResponse getPropertyIdsByRadius(
        @WebParam(name = "getPropertyIdsByRadiusRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsByRadiusRequest")
        GetPropertyIdsByRadiusRequest getPropertyIdsByRadiusRequest);

    /**
     * 
     * @param getPDFAVMRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetPDFAVMResponse>
     */
    @WebMethod(operationName = "getPDFAVM")
    public Response<GetPDFAVMResponse> getPDFAVMAsync(
        @WebParam(name = "getPDFAVMRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPDFAVMRequest")
        GetPDFAVMRequest getPDFAVMRequest);

    /**
     * 
     * @param getPDFAVMRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getPDFAVM")
    public Future<?> getPDFAVMAsync(
        @WebParam(name = "getPDFAVMRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPDFAVMRequest")
        GetPDFAVMRequest getPDFAVMRequest,
        @WebParam(name = "getPDFAVMResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetPDFAVMResponse> asyncHandler);

    /**
     * 
     * @param getPDFAVMRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetPDFAVMResponse
     */
    @WebMethod
    @WebResult(name = "getPDFAVMResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPDFAVMResponse")
    public GetPDFAVMResponse getPDFAVM(
        @WebParam(name = "getPDFAVMRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPDFAVMRequest")
        GetPDFAVMRequest getPDFAVMRequest);

    /**
     * 
     * @param getPropertyCoordinatesRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetPropertyCoordinatesResponse>
     */
    @WebMethod(operationName = "getPropertyCoordinates")
    public Response<GetPropertyCoordinatesResponse> getPropertyCoordinatesAsync(
        @WebParam(name = "getPropertyCoordinatesRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyCoordinatesRequest")
        GetPropertyCoordinatesRequest getPropertyCoordinatesRequest);

    /**
     * 
     * @param getPropertyCoordinatesRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getPropertyCoordinates")
    public Future<?> getPropertyCoordinatesAsync(
        @WebParam(name = "getPropertyCoordinatesRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyCoordinatesRequest")
        GetPropertyCoordinatesRequest getPropertyCoordinatesRequest,
        @WebParam(name = "getPropertyCoordinatesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetPropertyCoordinatesResponse> asyncHandler);

    /**
     * 
     * @param getPropertyCoordinatesRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetPropertyCoordinatesResponse
     */
    @WebMethod
    @WebResult(name = "getPropertyCoordinatesResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyCoordinatesResponse")
    public GetPropertyCoordinatesResponse getPropertyCoordinates(
        @WebParam(name = "getPropertyCoordinatesRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyCoordinatesRequest")
        GetPropertyCoordinatesRequest getPropertyCoordinatesRequest);

    /**
     * 
     * @param getHybridPDFAVMRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetHybridPDFAVMResponse>
     */
    @WebMethod(operationName = "getHybridPDFAVM")
    public Response<GetHybridPDFAVMResponse> getHybridPDFAVMAsync(
        @WebParam(name = "getHybridPDFAVMRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getHybridPDFAVMRequest")
        GetHybridPDFAVMRequest getHybridPDFAVMRequest);

    /**
     * 
     * @param getHybridPDFAVMRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getHybridPDFAVM")
    public Future<?> getHybridPDFAVMAsync(
        @WebParam(name = "getHybridPDFAVMRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getHybridPDFAVMRequest")
        GetHybridPDFAVMRequest getHybridPDFAVMRequest,
        @WebParam(name = "getHybridPDFAVMResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetHybridPDFAVMResponse> asyncHandler);

    /**
     * 
     * @param getHybridPDFAVMRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetHybridPDFAVMResponse
     */
    @WebMethod
    @WebResult(name = "getHybridPDFAVMResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getHybridPDFAVMResponse")
    public GetHybridPDFAVMResponse getHybridPDFAVM(
        @WebParam(name = "getHybridPDFAVMRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getHybridPDFAVMRequest")
        GetHybridPDFAVMRequest getHybridPDFAVMRequest);

    /**
     * 
     * @param getPropertyIdsByPropertyRadiusRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetPropertyIdsByPropertyRadiusResponse>
     */
    @WebMethod(operationName = "getPropertyIdsByPropertyRadius")
    public Response<GetPropertyIdsByPropertyRadiusResponse> getPropertyIdsByPropertyRadiusAsync(
        @WebParam(name = "getPropertyIdsByPropertyRadiusRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsByPropertyRadiusRequest")
        GetPropertyIdsByPropertyRadiusRequest getPropertyIdsByPropertyRadiusRequest);

    /**
     * 
     * @param getPropertyIdsByPropertyRadiusRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getPropertyIdsByPropertyRadius")
    public Future<?> getPropertyIdsByPropertyRadiusAsync(
        @WebParam(name = "getPropertyIdsByPropertyRadiusRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsByPropertyRadiusRequest")
        GetPropertyIdsByPropertyRadiusRequest getPropertyIdsByPropertyRadiusRequest,
        @WebParam(name = "getPropertyIdsByPropertyRadiusResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetPropertyIdsByPropertyRadiusResponse> asyncHandler);

    /**
     * 
     * @param getPropertyIdsByPropertyRadiusRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetPropertyIdsByPropertyRadiusResponse
     */
    @WebMethod
    @WebResult(name = "getPropertyIdsByPropertyRadiusResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsByPropertyRadiusResponse")
    public GetPropertyIdsByPropertyRadiusResponse getPropertyIdsByPropertyRadius(
        @WebParam(name = "getPropertyIdsByPropertyRadiusRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsByPropertyRadiusRequest")
        GetPropertyIdsByPropertyRadiusRequest getPropertyIdsByPropertyRadiusRequest);

    /**
     * 
     * @param getAVMRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetAVMResponse>
     */
    @WebMethod(operationName = "getAVM")
    public Response<GetAVMResponse> getAVMAsync(
        @WebParam(name = "getAVMRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getAVMRequest")
        GetAVMRequest getAVMRequest);

    /**
     * 
     * @param getAVMRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getAVM")
    public Future<?> getAVMAsync(
        @WebParam(name = "getAVMRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getAVMRequest")
        GetAVMRequest getAVMRequest,
        @WebParam(name = "getAVMResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetAVMResponse> asyncHandler);

    /**
     * 
     * @param getAVMRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetAVMResponse
     */
    @WebMethod
    @WebResult(name = "getAVMResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getAVMResponse")
    public GetAVMResponse getAVM(
        @WebParam(name = "getAVMRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getAVMRequest")
        GetAVMRequest getAVMRequest);

    /**
     * 
     * @param getSuggestionListRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetSuggestionListResponse>
     */
    @WebMethod(operationName = "getSuggestionList")
    public Response<GetSuggestionListResponse> getSuggestionListAsync(
        @WebParam(name = "getSuggestionListRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSuggestionListRequest")
        GetSuggestionListRequest getSuggestionListRequest);

    /**
     * 
     * @param asyncHandler
     * @param getSuggestionListRequest
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getSuggestionList")
    public Future<?> getSuggestionListAsync(
        @WebParam(name = "getSuggestionListRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSuggestionListRequest")
        GetSuggestionListRequest getSuggestionListRequest,
        @WebParam(name = "getSuggestionListResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetSuggestionListResponse> asyncHandler);

    /**
     * 
     * @param getSuggestionListRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetSuggestionListResponse
     */
    @WebMethod
    @WebResult(name = "getSuggestionListResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSuggestionListResponse")
    public GetSuggestionListResponse getSuggestionList(
        @WebParam(name = "getSuggestionListRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSuggestionListRequest")
        GetSuggestionListRequest getSuggestionListRequest);

    /**
     * 
     * @param getPropertyIdsForCompanyRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetPropertyIdsForCompanyResponse>
     */
    @WebMethod(operationName = "getPropertyIdsForCompany")
    public Response<GetPropertyIdsForCompanyResponse> getPropertyIdsForCompanyAsync(
        @WebParam(name = "getPropertyIdsForCompanyRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsForCompanyRequest")
        GetPropertyIdsForCompanyRequest getPropertyIdsForCompanyRequest);

    /**
     * 
     * @param getPropertyIdsForCompanyRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getPropertyIdsForCompany")
    public Future<?> getPropertyIdsForCompanyAsync(
        @WebParam(name = "getPropertyIdsForCompanyRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsForCompanyRequest")
        GetPropertyIdsForCompanyRequest getPropertyIdsForCompanyRequest,
        @WebParam(name = "getPropertyIdsForCompanyResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetPropertyIdsForCompanyResponse> asyncHandler);

    /**
     * 
     * @param getPropertyIdsForCompanyRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetPropertyIdsForCompanyResponse
     */
    @WebMethod
    @WebResult(name = "getPropertyIdsForCompanyResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsForCompanyResponse")
    public GetPropertyIdsForCompanyResponse getPropertyIdsForCompany(
        @WebParam(name = "getPropertyIdsForCompanyRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsForCompanyRequest")
        GetPropertyIdsForCompanyRequest getPropertyIdsForCompanyRequest);

    /**
     * 
     * @param doneCMARequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.DoneCMAResponse>
     */
    @WebMethod(operationName = "doneCMA")
    public Response<DoneCMAResponse> doneCMAAsync(
        @WebParam(name = "doneCMARequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "doneCMARequest")
        DoneCMARequest doneCMARequest);

    /**
     * 
     * @param doneCMARequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "doneCMA")
    public Future<?> doneCMAAsync(
        @WebParam(name = "doneCMARequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "doneCMARequest")
        DoneCMARequest doneCMARequest,
        @WebParam(name = "doneCMAResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<DoneCMAResponse> asyncHandler);

    /**
     * 
     * @param doneCMARequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.DoneCMAResponse
     */
    @WebMethod
    @WebResult(name = "doneCMAResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "doneCMAResponse")
    public DoneCMAResponse doneCMA(
        @WebParam(name = "doneCMARequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "doneCMARequest")
        DoneCMARequest doneCMARequest);

    /**
     * 
     * @param getPropertyAddressListFromSuggestionRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetPropertyAddressListFromSuggestionResponse>
     */
    @WebMethod(operationName = "getPropertyAddressListFromSuggestion")
    public Response<GetPropertyAddressListFromSuggestionResponse> getPropertyAddressListFromSuggestionAsync(
        @WebParam(name = "getPropertyAddressListFromSuggestionRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyAddressListFromSuggestionRequest")
        GetPropertyAddressListFromSuggestionRequest getPropertyAddressListFromSuggestionRequest);

    /**
     * 
     * @param getPropertyAddressListFromSuggestionRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getPropertyAddressListFromSuggestion")
    public Future<?> getPropertyAddressListFromSuggestionAsync(
        @WebParam(name = "getPropertyAddressListFromSuggestionRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyAddressListFromSuggestionRequest")
        GetPropertyAddressListFromSuggestionRequest getPropertyAddressListFromSuggestionRequest,
        @WebParam(name = "getPropertyAddressListFromSuggestionResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetPropertyAddressListFromSuggestionResponse> asyncHandler);

    /**
     * 
     * @param getPropertyAddressListFromSuggestionRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetPropertyAddressListFromSuggestionResponse
     */
    @WebMethod
    @WebResult(name = "getPropertyAddressListFromSuggestionResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyAddressListFromSuggestionResponse")
    public GetPropertyAddressListFromSuggestionResponse getPropertyAddressListFromSuggestion(
        @WebParam(name = "getPropertyAddressListFromSuggestionRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyAddressListFromSuggestionRequest")
        GetPropertyAddressListFromSuggestionRequest getPropertyAddressListFromSuggestionRequest);

    /**
     * 
     * @param getConfigAVMRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetConfigAVMResponse>
     */
    @WebMethod(operationName = "getConfigAVM")
    public Response<GetConfigAVMResponse> getConfigAVMAsync(
        @WebParam(name = "getConfigAVMRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getConfigAVMRequest")
        GetConfigAVMRequest getConfigAVMRequest);

    /**
     * 
     * @param asyncHandler
     * @param getConfigAVMRequest
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getConfigAVM")
    public Future<?> getConfigAVMAsync(
        @WebParam(name = "getConfigAVMRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getConfigAVMRequest")
        GetConfigAVMRequest getConfigAVMRequest,
        @WebParam(name = "getConfigAVMResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetConfigAVMResponse> asyncHandler);

    /**
     * 
     * @param getConfigAVMRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetConfigAVMResponse
     */
    @WebMethod
    @WebResult(name = "getConfigAVMResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getConfigAVMResponse")
    public GetConfigAVMResponse getConfigAVM(
        @WebParam(name = "getConfigAVMRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getConfigAVMRequest")
        GetConfigAVMRequest getConfigAVMRequest);

    /**
     * 
     * @param getPropertyIdsByTitleVolFolioRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetPropertyIdsByTitleVolFolioResponse>
     */
    @WebMethod(operationName = "getPropertyIdsByTitleVolFolio")
    public Response<GetPropertyIdsByTitleVolFolioResponse> getPropertyIdsByTitleVolFolioAsync(
        @WebParam(name = "getPropertyIdsByTitleVolFolioRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsByTitleVolFolioRequest")
        GetPropertyIdsByTitleVolFolioRequest getPropertyIdsByTitleVolFolioRequest);

    /**
     * 
     * @param asyncHandler
     * @param getPropertyIdsByTitleVolFolioRequest
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getPropertyIdsByTitleVolFolio")
    public Future<?> getPropertyIdsByTitleVolFolioAsync(
        @WebParam(name = "getPropertyIdsByTitleVolFolioRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsByTitleVolFolioRequest")
        GetPropertyIdsByTitleVolFolioRequest getPropertyIdsByTitleVolFolioRequest,
        @WebParam(name = "getPropertyIdsByTitleVolFolioResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetPropertyIdsByTitleVolFolioResponse> asyncHandler);

    /**
     * 
     * @param getPropertyIdsByTitleVolFolioRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetPropertyIdsByTitleVolFolioResponse
     */
    @WebMethod
    @WebResult(name = "getPropertyIdsByTitleVolFolioResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsByTitleVolFolioResponse")
    public GetPropertyIdsByTitleVolFolioResponse getPropertyIdsByTitleVolFolio(
        @WebParam(name = "getPropertyIdsByTitleVolFolioRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsByTitleVolFolioRequest")
        GetPropertyIdsByTitleVolFolioRequest getPropertyIdsByTitleVolFolioRequest);

    /**
     * 
     * @param refinePropertiesRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.RefinePropertiesResponse>
     */
    @WebMethod(operationName = "refineProperties")
    public Response<RefinePropertiesResponse> refinePropertiesAsync(
        @WebParam(name = "refinePropertiesRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "refinePropertiesRequest")
        RefinePropertiesRequest refinePropertiesRequest);

    /**
     * 
     * @param asyncHandler
     * @param refinePropertiesRequest
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "refineProperties")
    public Future<?> refinePropertiesAsync(
        @WebParam(name = "refinePropertiesRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "refinePropertiesRequest")
        RefinePropertiesRequest refinePropertiesRequest,
        @WebParam(name = "refinePropertiesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<RefinePropertiesResponse> asyncHandler);

    /**
     * 
     * @param refinePropertiesRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.RefinePropertiesResponse
     */
    @WebMethod
    @WebResult(name = "refinePropertiesResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "refinePropertiesResponse")
    public RefinePropertiesResponse refineProperties(
        @WebParam(name = "refinePropertiesRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "refinePropertiesRequest")
        RefinePropertiesRequest refinePropertiesRequest);

    /**
     * 
     * @param getPropertyIdsByPlanRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetPropertyIdsByPlanResponse>
     */
    @WebMethod(operationName = "getPropertyIdsByPlan")
    public Response<GetPropertyIdsByPlanResponse> getPropertyIdsByPlanAsync(
        @WebParam(name = "getPropertyIdsByPlanRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsByPlanRequest")
        GetPropertyIdsByPlanRequest getPropertyIdsByPlanRequest);

    /**
     * 
     * @param getPropertyIdsByPlanRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getPropertyIdsByPlan")
    public Future<?> getPropertyIdsByPlanAsync(
        @WebParam(name = "getPropertyIdsByPlanRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsByPlanRequest")
        GetPropertyIdsByPlanRequest getPropertyIdsByPlanRequest,
        @WebParam(name = "getPropertyIdsByPlanResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetPropertyIdsByPlanResponse> asyncHandler);

    /**
     * 
     * @param getPropertyIdsByPlanRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetPropertyIdsByPlanResponse
     */
    @WebMethod
    @WebResult(name = "getPropertyIdsByPlanResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsByPlanResponse")
    public GetPropertyIdsByPlanResponse getPropertyIdsByPlan(
        @WebParam(name = "getPropertyIdsByPlanRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsByPlanRequest")
        GetPropertyIdsByPlanRequest getPropertyIdsByPlanRequest);

    /**
     * 
     * @param getPropertySummaryListRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetPropertySummaryListResponse>
     */
    @WebMethod(operationName = "getPropertySummaryList")
    public Response<GetPropertySummaryListResponse> getPropertySummaryListAsync(
        @WebParam(name = "getPropertySummaryListRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertySummaryListRequest")
        GetPropertySummaryListRequest getPropertySummaryListRequest);

    /**
     * 
     * @param asyncHandler
     * @param getPropertySummaryListRequest
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getPropertySummaryList")
    public Future<?> getPropertySummaryListAsync(
        @WebParam(name = "getPropertySummaryListRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertySummaryListRequest")
        GetPropertySummaryListRequest getPropertySummaryListRequest,
        @WebParam(name = "getPropertySummaryListResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetPropertySummaryListResponse> asyncHandler);

    /**
     * 
     * @param getPropertySummaryListRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetPropertySummaryListResponse
     */
    @WebMethod
    @WebResult(name = "getPropertySummaryListResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertySummaryListResponse")
    public GetPropertySummaryListResponse getPropertySummaryList(
        @WebParam(name = "getPropertySummaryListRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertySummaryListRequest")
        GetPropertySummaryListRequest getPropertySummaryListRequest);

    /**
     * 
     * @param getLookupValuesRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetLookupValuesResponse>
     */
    @WebMethod(operationName = "getLookupValues")
    public Response<GetLookupValuesResponse> getLookupValuesAsync(
        @WebParam(name = "getLookupValuesRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getLookupValuesRequest")
        GetLookupValuesRequest getLookupValuesRequest);

    /**
     * 
     * @param getLookupValuesRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getLookupValues")
    public Future<?> getLookupValuesAsync(
        @WebParam(name = "getLookupValuesRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getLookupValuesRequest")
        GetLookupValuesRequest getLookupValuesRequest,
        @WebParam(name = "getLookupValuesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetLookupValuesResponse> asyncHandler);

    /**
     * 
     * @param getLookupValuesRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetLookupValuesResponse
     */
    @WebMethod
    @WebResult(name = "getLookupValuesResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getLookupValuesResponse")
    public GetLookupValuesResponse getLookupValues(
        @WebParam(name = "getLookupValuesRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getLookupValuesRequest")
        GetLookupValuesRequest getLookupValuesRequest);

    /**
     * 
     * @param getPropertyIdsByNameRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetPropertyIdsByNameResponse>
     */
    @WebMethod(operationName = "getPropertyIdsByName")
    public Response<GetPropertyIdsByNameResponse> getPropertyIdsByNameAsync(
        @WebParam(name = "getPropertyIdsByNameRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsByNameRequest")
        GetPropertyIdsByNameRequest getPropertyIdsByNameRequest);

    /**
     * 
     * @param asyncHandler
     * @param getPropertyIdsByNameRequest
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getPropertyIdsByName")
    public Future<?> getPropertyIdsByNameAsync(
        @WebParam(name = "getPropertyIdsByNameRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsByNameRequest")
        GetPropertyIdsByNameRequest getPropertyIdsByNameRequest,
        @WebParam(name = "getPropertyIdsByNameResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetPropertyIdsByNameResponse> asyncHandler);

    /**
     * 
     * @param getPropertyIdsByNameRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetPropertyIdsByNameResponse
     */
    @WebMethod
    @WebResult(name = "getPropertyIdsByNameResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsByNameResponse")
    public GetPropertyIdsByNameResponse getPropertyIdsByName(
        @WebParam(name = "getPropertyIdsByNameRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsByNameRequest")
        GetPropertyIdsByNameRequest getPropertyIdsByNameRequest);

    /**
     * 
     * @param getRismarkAVMRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetRismarkAVMResponse>
     */
    @WebMethod(operationName = "getRismarkAVM")
    public Response<GetRismarkAVMResponse> getRismarkAVMAsync(
        @WebParam(name = "getRismarkAVMRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getRismarkAVMRequest")
        GetRismarkAVMRequest getRismarkAVMRequest);

    /**
     * 
     * @param getRismarkAVMRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getRismarkAVM")
    public Future<?> getRismarkAVMAsync(
        @WebParam(name = "getRismarkAVMRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getRismarkAVMRequest")
        GetRismarkAVMRequest getRismarkAVMRequest,
        @WebParam(name = "getRismarkAVMResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetRismarkAVMResponse> asyncHandler);

    /**
     * 
     * @param getRismarkAVMRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetRismarkAVMResponse
     */
    @WebMethod
    @WebResult(name = "getRismarkAVMResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getRismarkAVMResponse")
    public GetRismarkAVMResponse getRismarkAVM(
        @WebParam(name = "getRismarkAVMRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getRismarkAVMRequest")
        GetRismarkAVMRequest getRismarkAVMRequest);

    /**
     * 
     * @param getPropertyIdsForAreaRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetPropertyIdsForAreaResponse>
     */
    @WebMethod(operationName = "getPropertyIdsForArea")
    public Response<GetPropertyIdsForAreaResponse> getPropertyIdsForAreaAsync(
        @WebParam(name = "getPropertyIdsForAreaRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsForAreaRequest")
        GetPropertyIdsForAreaRequest getPropertyIdsForAreaRequest);

    /**
     * 
     * @param asyncHandler
     * @param getPropertyIdsForAreaRequest
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getPropertyIdsForArea")
    public Future<?> getPropertyIdsForAreaAsync(
        @WebParam(name = "getPropertyIdsForAreaRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsForAreaRequest")
        GetPropertyIdsForAreaRequest getPropertyIdsForAreaRequest,
        @WebParam(name = "getPropertyIdsForAreaResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetPropertyIdsForAreaResponse> asyncHandler);

    /**
     * 
     * @param getPropertyIdsForAreaRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetPropertyIdsForAreaResponse
     */
    @WebMethod
    @WebResult(name = "getPropertyIdsForAreaResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsForAreaResponse")
    public GetPropertyIdsForAreaResponse getPropertyIdsForArea(
        @WebParam(name = "getPropertyIdsForAreaRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsForAreaRequest")
        GetPropertyIdsForAreaRequest getPropertyIdsForAreaRequest);

    /**
     * 
     * @param getPropertySummaryRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetPropertySummaryResponse>
     */
    @WebMethod(operationName = "getPropertySummary")
    public Response<GetPropertySummaryResponse> getPropertySummaryAsync(
        @WebParam(name = "getPropertySummaryRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertySummaryRequest")
        GetPropertySummaryRequest getPropertySummaryRequest);

    /**
     * 
     * @param asyncHandler
     * @param getPropertySummaryRequest
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getPropertySummary")
    public Future<?> getPropertySummaryAsync(
        @WebParam(name = "getPropertySummaryRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertySummaryRequest")
        GetPropertySummaryRequest getPropertySummaryRequest,
        @WebParam(name = "getPropertySummaryResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetPropertySummaryResponse> asyncHandler);

    /**
     * 
     * @param getPropertySummaryRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetPropertySummaryResponse
     */
    @WebMethod
    @WebResult(name = "getPropertySummaryResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertySummaryResponse")
    public GetPropertySummaryResponse getPropertySummary(
        @WebParam(name = "getPropertySummaryRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertySummaryRequest")
        GetPropertySummaryRequest getPropertySummaryRequest);

    /**
     * 
     * @param getPropertyDetailRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetPropertyDetailResponse>
     */
    @WebMethod(operationName = "getPropertyDetail")
    public Response<GetPropertyDetailResponse> getPropertyDetailAsync(
        @WebParam(name = "getPropertyDetailRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyDetailRequest")
        GetPropertyDetailRequest getPropertyDetailRequest);

    /**
     * 
     * @param asyncHandler
     * @param getPropertyDetailRequest
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getPropertyDetail")
    public Future<?> getPropertyDetailAsync(
        @WebParam(name = "getPropertyDetailRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyDetailRequest")
        GetPropertyDetailRequest getPropertyDetailRequest,
        @WebParam(name = "getPropertyDetailResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetPropertyDetailResponse> asyncHandler);

    /**
     * 
     * @param getPropertyDetailRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetPropertyDetailResponse
     */
    @WebMethod
    @WebResult(name = "getPropertyDetailResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyDetailResponse")
    public GetPropertyDetailResponse getPropertyDetail(
        @WebParam(name = "getPropertyDetailRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyDetailRequest")
        GetPropertyDetailRequest getPropertyDetailRequest);

    /**
     * 
     * @param getAvailableAttributesForPropertyIdsRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetAvailableAttributesForPropertyIdsResponse>
     */
    @WebMethod(operationName = "getAvailableAttributesForPropertyIds")
    public Response<GetAvailableAttributesForPropertyIdsResponse> getAvailableAttributesForPropertyIdsAsync(
        @WebParam(name = "getAvailableAttributesForPropertyIdsRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getAvailableAttributesForPropertyIdsRequest")
        GetAvailableAttributesForPropertyIdsRequest getAvailableAttributesForPropertyIdsRequest);

    /**
     * 
     * @param asyncHandler
     * @param getAvailableAttributesForPropertyIdsRequest
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getAvailableAttributesForPropertyIds")
    public Future<?> getAvailableAttributesForPropertyIdsAsync(
        @WebParam(name = "getAvailableAttributesForPropertyIdsRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getAvailableAttributesForPropertyIdsRequest")
        GetAvailableAttributesForPropertyIdsRequest getAvailableAttributesForPropertyIdsRequest,
        @WebParam(name = "getAvailableAttributesForPropertyIdsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetAvailableAttributesForPropertyIdsResponse> asyncHandler);

    /**
     * 
     * @param getAvailableAttributesForPropertyIdsRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetAvailableAttributesForPropertyIdsResponse
     */
    @WebMethod
    @WebResult(name = "getAvailableAttributesForPropertyIdsResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getAvailableAttributesForPropertyIdsResponse")
    public GetAvailableAttributesForPropertyIdsResponse getAvailableAttributesForPropertyIds(
        @WebParam(name = "getAvailableAttributesForPropertyIdsRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getAvailableAttributesForPropertyIdsRequest")
        GetAvailableAttributesForPropertyIdsRequest getAvailableAttributesForPropertyIdsRequest);

    /**
     * 
     * @param getHybridAVMRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetHybridAVMResponse>
     */
    @WebMethod(operationName = "getHybridAVM")
    public Response<GetHybridAVMResponse> getHybridAVMAsync(
        @WebParam(name = "getHybridAVMRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getHybridAVMRequest")
        GetHybridAVMRequest getHybridAVMRequest);

    /**
     * 
     * @param getHybridAVMRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getHybridAVM")
    public Future<?> getHybridAVMAsync(
        @WebParam(name = "getHybridAVMRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getHybridAVMRequest")
        GetHybridAVMRequest getHybridAVMRequest,
        @WebParam(name = "getHybridAVMResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetHybridAVMResponse> asyncHandler);

    /**
     * 
     * @param getHybridAVMRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetHybridAVMResponse
     */
    @WebMethod
    @WebResult(name = "getHybridAVMResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getHybridAVMResponse")
    public GetHybridAVMResponse getHybridAVM(
        @WebParam(name = "getHybridAVMRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getHybridAVMRequest")
        GetHybridAVMRequest getHybridAVMRequest);

    /**
     * 
     * @param getPropertyIdListFromSuggestionRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetPropertyIdListFromSuggestionResponse>
     */
    @WebMethod(operationName = "getPropertyIdListFromSuggestion")
    public Response<GetPropertyIdListFromSuggestionResponse> getPropertyIdListFromSuggestionAsync(
        @WebParam(name = "getPropertyIdListFromSuggestionRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdListFromSuggestionRequest")
        GetPropertyIdListFromSuggestionRequest getPropertyIdListFromSuggestionRequest);

    /**
     * 
     * @param asyncHandler
     * @param getPropertyIdListFromSuggestionRequest
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getPropertyIdListFromSuggestion")
    public Future<?> getPropertyIdListFromSuggestionAsync(
        @WebParam(name = "getPropertyIdListFromSuggestionRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdListFromSuggestionRequest")
        GetPropertyIdListFromSuggestionRequest getPropertyIdListFromSuggestionRequest,
        @WebParam(name = "getPropertyIdListFromSuggestionResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetPropertyIdListFromSuggestionResponse> asyncHandler);

    /**
     * 
     * @param getPropertyIdListFromSuggestionRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetPropertyIdListFromSuggestionResponse
     */
    @WebMethod
    @WebResult(name = "getPropertyIdListFromSuggestionResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdListFromSuggestionResponse")
    public GetPropertyIdListFromSuggestionResponse getPropertyIdListFromSuggestion(
        @WebParam(name = "getPropertyIdListFromSuggestionRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdListFromSuggestionRequest")
        GetPropertyIdListFromSuggestionRequest getPropertyIdListFromSuggestionRequest);

    /**
     * 
     * @param getAddressMatchRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetAddressMatchResponse>
     */
    @WebMethod(operationName = "getAddressMatch")
    public Response<GetAddressMatchResponse> getAddressMatchAsync(
        @WebParam(name = "getAddressMatchRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getAddressMatchRequest")
        GetAddressMatchRequest getAddressMatchRequest);

    /**
     * 
     * @param getAddressMatchRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getAddressMatch")
    public Future<?> getAddressMatchAsync(
        @WebParam(name = "getAddressMatchRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getAddressMatchRequest")
        GetAddressMatchRequest getAddressMatchRequest,
        @WebParam(name = "getAddressMatchResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetAddressMatchResponse> asyncHandler);

    /**
     * 
     * @param getAddressMatchRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetAddressMatchResponse
     */
    @WebMethod
    @WebResult(name = "getAddressMatchResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getAddressMatchResponse")
    public GetAddressMatchResponse getAddressMatch(
        @WebParam(name = "getAddressMatchRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getAddressMatchRequest")
        GetAddressMatchRequest getAddressMatchRequest);

    /**
     * 
     * @param getPropertyIdsByTitleRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetPropertyIdsByTitleResponse>
     */
    @WebMethod(operationName = "getPropertyIdsByTitle")
    public Response<GetPropertyIdsByTitleResponse> getPropertyIdsByTitleAsync(
        @WebParam(name = "getPropertyIdsByTitleRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsByTitleRequest")
        GetPropertyIdsByTitleRequest getPropertyIdsByTitleRequest);

    /**
     * 
     * @param getPropertyIdsByTitleRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getPropertyIdsByTitle")
    public Future<?> getPropertyIdsByTitleAsync(
        @WebParam(name = "getPropertyIdsByTitleRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsByTitleRequest")
        GetPropertyIdsByTitleRequest getPropertyIdsByTitleRequest,
        @WebParam(name = "getPropertyIdsByTitleResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetPropertyIdsByTitleResponse> asyncHandler);

    /**
     * 
     * @param getPropertyIdsByTitleRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetPropertyIdsByTitleResponse
     */
    @WebMethod
    @WebResult(name = "getPropertyIdsByTitleResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsByTitleResponse")
    public GetPropertyIdsByTitleResponse getPropertyIdsByTitle(
        @WebParam(name = "getPropertyIdsByTitleRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsByTitleRequest")
        GetPropertyIdsByTitleRequest getPropertyIdsByTitleRequest);

    /**
     * 
     * @param getPropertyIdsBySectionRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.clientnz.GetPropertyIdsBySectionResponse>
     */
    @WebMethod(operationName = "getPropertyIdsBySection")
    public Response<GetPropertyIdsBySectionResponse> getPropertyIdsBySectionAsync(
        @WebParam(name = "getPropertyIdsBySectionRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsBySectionRequest")
        GetPropertyIdsBySectionRequest getPropertyIdsBySectionRequest);

    /**
     * 
     * @param asyncHandler
     * @param getPropertyIdsBySectionRequest
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getPropertyIdsBySection")
    public Future<?> getPropertyIdsBySectionAsync(
        @WebParam(name = "getPropertyIdsBySectionRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsBySectionRequest")
        GetPropertyIdsBySectionRequest getPropertyIdsBySectionRequest,
        @WebParam(name = "getPropertyIdsBySectionResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetPropertyIdsBySectionResponse> asyncHandler);

    /**
     * 
     * @param getPropertyIdsBySectionRequest
     * @return
     *     returns com.tooltwist.bsg.clientnz.GetPropertyIdsBySectionResponse
     */
    @WebMethod
    @WebResult(name = "getPropertyIdsBySectionResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsBySectionResponse")
    public GetPropertyIdsBySectionResponse getPropertyIdsBySection(
        @WebParam(name = "getPropertyIdsBySectionRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getPropertyIdsBySectionRequest")
        GetPropertyIdsBySectionRequest getPropertyIdsBySectionRequest);

}
