
package com.tooltwist.bsg.clientnz;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PropertyServiceService", targetNamespace = "http://rpdata.com/bsg/schemas", wsdlLocation = "http://rpp.rpdata.com/bsgNZ-2.0/ws/propertyService.wsdl")
public class PropertyServiceService
    extends Service
{

    private final static URL PROPERTYSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PROPERTYSERVICESERVICE_EXCEPTION;
    private final static QName PROPERTYSERVICESERVICE_QNAME = new QName("http://rpdata.com/bsg/schemas", "PropertyServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://rpp.rpdata.com/bsgNZ-2.0/ws/propertyService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROPERTYSERVICESERVICE_WSDL_LOCATION = url;
        PROPERTYSERVICESERVICE_EXCEPTION = e;
    }

    public PropertyServiceService() {
        super(__getWsdlLocation(), PROPERTYSERVICESERVICE_QNAME);
    }

    public PropertyServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROPERTYSERVICESERVICE_QNAME, features);
    }

    public PropertyServiceService(URL wsdlLocation) {
        super(wsdlLocation, PROPERTYSERVICESERVICE_QNAME);
    }

    public PropertyServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROPERTYSERVICESERVICE_QNAME, features);
    }

    public PropertyServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PropertyServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PropertyService
     */
    @WebEndpoint(name = "PropertyServiceSoap11")
    public PropertyService getPropertyServiceSoap11() {
        return super.getPort(new QName("http://rpdata.com/bsg/schemas", "PropertyServiceSoap11"), PropertyService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PropertyService
     */
    @WebEndpoint(name = "PropertyServiceSoap11")
    public PropertyService getPropertyServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://rpdata.com/bsg/schemas", "PropertyServiceSoap11"), PropertyService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROPERTYSERVICESERVICE_EXCEPTION!= null) {
            throw PROPERTYSERVICESERVICE_EXCEPTION;
        }
        return PROPERTYSERVICESERVICE_WSDL_LOCATION;
    }

}
