
package com.tooltwist.bsg.clientnz;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PropertyStatisticsServiceService", targetNamespace = "http://rpdata.com/bsg/schemas", wsdlLocation = "http://rpp.rpdata.com/bsgNZ-2.0/ws/propertyStatisticsService.wsdl")
public class PropertyStatisticsServiceService
    extends Service
{

    private final static URL PROPERTYSTATISTICSSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PROPERTYSTATISTICSSERVICESERVICE_EXCEPTION;
    private final static QName PROPERTYSTATISTICSSERVICESERVICE_QNAME = new QName("http://rpdata.com/bsg/schemas", "PropertyStatisticsServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://rpp.rpdata.com/bsgNZ-2.0/ws/propertyStatisticsService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROPERTYSTATISTICSSERVICESERVICE_WSDL_LOCATION = url;
        PROPERTYSTATISTICSSERVICESERVICE_EXCEPTION = e;
    }

    public PropertyStatisticsServiceService() {
        super(__getWsdlLocation(), PROPERTYSTATISTICSSERVICESERVICE_QNAME);
    }

    public PropertyStatisticsServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROPERTYSTATISTICSSERVICESERVICE_QNAME, features);
    }

    public PropertyStatisticsServiceService(URL wsdlLocation) {
        super(wsdlLocation, PROPERTYSTATISTICSSERVICESERVICE_QNAME);
    }

    public PropertyStatisticsServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROPERTYSTATISTICSSERVICESERVICE_QNAME, features);
    }

    public PropertyStatisticsServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PropertyStatisticsServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PropertyStatisticsService
     */
    @WebEndpoint(name = "PropertyStatisticsServiceSoap11")
    public PropertyStatisticsService getPropertyStatisticsServiceSoap11() {
        return super.getPort(new QName("http://rpdata.com/bsg/schemas", "PropertyStatisticsServiceSoap11"), PropertyStatisticsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PropertyStatisticsService
     */
    @WebEndpoint(name = "PropertyStatisticsServiceSoap11")
    public PropertyStatisticsService getPropertyStatisticsServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://rpdata.com/bsg/schemas", "PropertyStatisticsServiceSoap11"), PropertyStatisticsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROPERTYSTATISTICSSERVICESERVICE_EXCEPTION!= null) {
            throw PROPERTYSTATISTICSSERVICESERVICE_EXCEPTION;
        }
        return PROPERTYSTATISTICSSERVICESERVICE_WSDL_LOCATION;
    }

}
