
package com.tooltwist.bsg.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AuGovernmentStatisticsServiceService", targetNamespace = "http://rpdata.com/bsg/schemas", wsdlLocation = "http://rpp.rpdata.com/bsgAU-2.0/ws/auGovernmentStatisticsService.wsdl")
public class AuGovernmentStatisticsServiceService
    extends Service
{

    private final static URL AUGOVERNMENTSTATISTICSSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException AUGOVERNMENTSTATISTICSSERVICESERVICE_EXCEPTION;
    private final static QName AUGOVERNMENTSTATISTICSSERVICESERVICE_QNAME = new QName("http://rpdata.com/bsg/schemas", "AuGovernmentStatisticsServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://rpp.rpdata.com/bsgAU-2.0/ws/auGovernmentStatisticsService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUGOVERNMENTSTATISTICSSERVICESERVICE_WSDL_LOCATION = url;
        AUGOVERNMENTSTATISTICSSERVICESERVICE_EXCEPTION = e;
    }

    public AuGovernmentStatisticsServiceService() {
        super(__getWsdlLocation(), AUGOVERNMENTSTATISTICSSERVICESERVICE_QNAME);
    }

    public AuGovernmentStatisticsServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUGOVERNMENTSTATISTICSSERVICESERVICE_QNAME, features);
    }

    public AuGovernmentStatisticsServiceService(URL wsdlLocation) {
        super(wsdlLocation, AUGOVERNMENTSTATISTICSSERVICESERVICE_QNAME);
    }

    public AuGovernmentStatisticsServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUGOVERNMENTSTATISTICSSERVICESERVICE_QNAME, features);
    }

    public AuGovernmentStatisticsServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuGovernmentStatisticsServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AuGovernmentStatisticsService
     */
    @WebEndpoint(name = "AuGovernmentStatisticsServiceSoap11")
    public AuGovernmentStatisticsService getAuGovernmentStatisticsServiceSoap11() {
        return super.getPort(new QName("http://rpdata.com/bsg/schemas", "AuGovernmentStatisticsServiceSoap11"), AuGovernmentStatisticsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuGovernmentStatisticsService
     */
    @WebEndpoint(name = "AuGovernmentStatisticsServiceSoap11")
    public AuGovernmentStatisticsService getAuGovernmentStatisticsServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://rpdata.com/bsg/schemas", "AuGovernmentStatisticsServiceSoap11"), AuGovernmentStatisticsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUGOVERNMENTSTATISTICSSERVICESERVICE_EXCEPTION!= null) {
            throw AUGOVERNMENTSTATISTICSSERVICESERVICE_EXCEPTION;
        }
        return AUGOVERNMENTSTATISTICSSERVICESERVICE_WSDL_LOCATION;
    }

}
