
package com.tooltwist.bsg.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MarketCompareServiceService", targetNamespace = "http://rpdata.com/bsg/schemas", wsdlLocation = "http://rpp.rpdata.com/bsgAU-2.0/ws/marketCompareService.wsdl")
public class MarketCompareServiceService
    extends Service
{

    private final static URL MARKETCOMPARESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException MARKETCOMPARESERVICESERVICE_EXCEPTION;
    private final static QName MARKETCOMPARESERVICESERVICE_QNAME = new QName("http://rpdata.com/bsg/schemas", "MarketCompareServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://rpp.rpdata.com/bsgAU-2.0/ws/marketCompareService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MARKETCOMPARESERVICESERVICE_WSDL_LOCATION = url;
        MARKETCOMPARESERVICESERVICE_EXCEPTION = e;
    }

    public MarketCompareServiceService() {
        super(__getWsdlLocation(), MARKETCOMPARESERVICESERVICE_QNAME);
    }

    public MarketCompareServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MARKETCOMPARESERVICESERVICE_QNAME, features);
    }

    public MarketCompareServiceService(URL wsdlLocation) {
        super(wsdlLocation, MARKETCOMPARESERVICESERVICE_QNAME);
    }

    public MarketCompareServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MARKETCOMPARESERVICESERVICE_QNAME, features);
    }

    public MarketCompareServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MarketCompareServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MarketCompareService
     */
    @WebEndpoint(name = "MarketCompareServiceSoap11")
    public MarketCompareService getMarketCompareServiceSoap11() {
        return super.getPort(new QName("http://rpdata.com/bsg/schemas", "MarketCompareServiceSoap11"), MarketCompareService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MarketCompareService
     */
    @WebEndpoint(name = "MarketCompareServiceSoap11")
    public MarketCompareService getMarketCompareServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://rpdata.com/bsg/schemas", "MarketCompareServiceSoap11"), MarketCompareService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MARKETCOMPARESERVICESERVICE_EXCEPTION!= null) {
            throw MARKETCOMPARESERVICESERVICE_EXCEPTION;
        }
        return MARKETCOMPARESERVICESERVICE_WSDL_LOCATION;
    }

}
