
package com.tooltwist.bsg.client;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PropertyStatisticsService", targetNamespace = "http://rpdata.com/bsg/schemas")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PropertyStatisticsService {


    /**
     * 
     * @param getYearlyMedianPricesRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.client.GetYearlyMedianPricesResponse>
     */
    @WebMethod(operationName = "getYearlyMedianPrices")
    public Response<GetYearlyMedianPricesResponse> getYearlyMedianPricesAsync(
        @WebParam(name = "getYearlyMedianPricesRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getYearlyMedianPricesRequest")
        GetYearlyMedianPricesRequest getYearlyMedianPricesRequest);

    /**
     * 
     * @param getYearlyMedianPricesRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getYearlyMedianPrices")
    public Future<?> getYearlyMedianPricesAsync(
        @WebParam(name = "getYearlyMedianPricesRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getYearlyMedianPricesRequest")
        GetYearlyMedianPricesRequest getYearlyMedianPricesRequest,
        @WebParam(name = "getYearlyMedianPricesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetYearlyMedianPricesResponse> asyncHandler);

    /**
     * 
     * @param getYearlyMedianPricesRequest
     * @return
     *     returns com.tooltwist.bsg.client.GetYearlyMedianPricesResponse
     */
    @WebMethod
    @WebResult(name = "getYearlyMedianPricesResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getYearlyMedianPricesResponse")
    public GetYearlyMedianPricesResponse getYearlyMedianPrices(
        @WebParam(name = "getYearlyMedianPricesRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getYearlyMedianPricesRequest")
        GetYearlyMedianPricesRequest getYearlyMedianPricesRequest);

    /**
     * 
     * @param getCapitalGrowthChartURLRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.client.GetCapitalGrowthChartURLResponse>
     */
    @WebMethod(operationName = "getCapitalGrowthChartURL")
    public Response<GetCapitalGrowthChartURLResponse> getCapitalGrowthChartURLAsync(
        @WebParam(name = "getCapitalGrowthChartURLRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getCapitalGrowthChartURLRequest")
        GetCapitalGrowthChartURLRequest getCapitalGrowthChartURLRequest);

    /**
     * 
     * @param getCapitalGrowthChartURLRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getCapitalGrowthChartURL")
    public Future<?> getCapitalGrowthChartURLAsync(
        @WebParam(name = "getCapitalGrowthChartURLRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getCapitalGrowthChartURLRequest")
        GetCapitalGrowthChartURLRequest getCapitalGrowthChartURLRequest,
        @WebParam(name = "getCapitalGrowthChartURLResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetCapitalGrowthChartURLResponse> asyncHandler);

    /**
     * 
     * @param getCapitalGrowthChartURLRequest
     * @return
     *     returns com.tooltwist.bsg.client.GetCapitalGrowthChartURLResponse
     */
    @WebMethod
    @WebResult(name = "getCapitalGrowthChartURLResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getCapitalGrowthChartURLResponse")
    public GetCapitalGrowthChartURLResponse getCapitalGrowthChartURL(
        @WebParam(name = "getCapitalGrowthChartURLRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getCapitalGrowthChartURLRequest")
        GetCapitalGrowthChartURLRequest getCapitalGrowthChartURLRequest);

    /**
     * 
     * @param getAreaProfileMedianPricesChartURLRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.client.GetAreaProfileMedianPricesChartURLResponse>
     */
    @WebMethod(operationName = "getAreaProfileMedianPricesChartURL")
    public Response<GetAreaProfileMedianPricesChartURLResponse> getAreaProfileMedianPricesChartURLAsync(
        @WebParam(name = "getAreaProfileMedianPricesChartURLRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getAreaProfileMedianPricesChartURLRequest")
        GetAreaProfileMedianPricesChartURLRequest getAreaProfileMedianPricesChartURLRequest);

    /**
     * 
     * @param getAreaProfileMedianPricesChartURLRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getAreaProfileMedianPricesChartURL")
    public Future<?> getAreaProfileMedianPricesChartURLAsync(
        @WebParam(name = "getAreaProfileMedianPricesChartURLRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getAreaProfileMedianPricesChartURLRequest")
        GetAreaProfileMedianPricesChartURLRequest getAreaProfileMedianPricesChartURLRequest,
        @WebParam(name = "getAreaProfileMedianPricesChartURLResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetAreaProfileMedianPricesChartURLResponse> asyncHandler);

    /**
     * 
     * @param getAreaProfileMedianPricesChartURLRequest
     * @return
     *     returns com.tooltwist.bsg.client.GetAreaProfileMedianPricesChartURLResponse
     */
    @WebMethod
    @WebResult(name = "getAreaProfileMedianPricesChartURLResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getAreaProfileMedianPricesChartURLResponse")
    public GetAreaProfileMedianPricesChartURLResponse getAreaProfileMedianPricesChartURL(
        @WebParam(name = "getAreaProfileMedianPricesChartURLRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getAreaProfileMedianPricesChartURLRequest")
        GetAreaProfileMedianPricesChartURLRequest getAreaProfileMedianPricesChartURLRequest);

    /**
     * 
     * @param getSuburbDetailsRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.client.GetSuburbDetailsResponse>
     */
    @WebMethod(operationName = "getSuburbDetails")
    public Response<GetSuburbDetailsResponse> getSuburbDetailsAsync(
        @WebParam(name = "getSuburbDetailsRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSuburbDetailsRequest")
        GetSuburbDetailsRequest getSuburbDetailsRequest);

    /**
     * 
     * @param getSuburbDetailsRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getSuburbDetails")
    public Future<?> getSuburbDetailsAsync(
        @WebParam(name = "getSuburbDetailsRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSuburbDetailsRequest")
        GetSuburbDetailsRequest getSuburbDetailsRequest,
        @WebParam(name = "getSuburbDetailsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetSuburbDetailsResponse> asyncHandler);

    /**
     * 
     * @param getSuburbDetailsRequest
     * @return
     *     returns com.tooltwist.bsg.client.GetSuburbDetailsResponse
     */
    @WebMethod
    @WebResult(name = "getSuburbDetailsResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSuburbDetailsResponse")
    public GetSuburbDetailsResponse getSuburbDetails(
        @WebParam(name = "getSuburbDetailsRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSuburbDetailsRequest")
        GetSuburbDetailsRequest getSuburbDetailsRequest);

    /**
     * 
     * @param getSalesByPriceChartURLRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.client.GetSalesByPriceChartURLResponse>
     */
    @WebMethod(operationName = "getSalesByPriceChartURL")
    public Response<GetSalesByPriceChartURLResponse> getSalesByPriceChartURLAsync(
        @WebParam(name = "getSalesByPriceChartURLRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSalesByPriceChartURLRequest")
        GetSalesByPriceChartURLRequest getSalesByPriceChartURLRequest);

    /**
     * 
     * @param asyncHandler
     * @param getSalesByPriceChartURLRequest
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getSalesByPriceChartURL")
    public Future<?> getSalesByPriceChartURLAsync(
        @WebParam(name = "getSalesByPriceChartURLRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSalesByPriceChartURLRequest")
        GetSalesByPriceChartURLRequest getSalesByPriceChartURLRequest,
        @WebParam(name = "getSalesByPriceChartURLResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetSalesByPriceChartURLResponse> asyncHandler);

    /**
     * 
     * @param getSalesByPriceChartURLRequest
     * @return
     *     returns com.tooltwist.bsg.client.GetSalesByPriceChartURLResponse
     */
    @WebMethod
    @WebResult(name = "getSalesByPriceChartURLResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSalesByPriceChartURLResponse")
    public GetSalesByPriceChartURLResponse getSalesByPriceChartURL(
        @WebParam(name = "getSalesByPriceChartURLRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSalesByPriceChartURLRequest")
        GetSalesByPriceChartURLRequest getSalesByPriceChartURLRequest);

    /**
     * 
     * @param getYearlyMedianPricesChartURLRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.client.GetYearlyMedianPricesChartURLResponse>
     */
    @WebMethod(operationName = "getYearlyMedianPricesChartURL")
    public Response<GetYearlyMedianPricesChartURLResponse> getYearlyMedianPricesChartURLAsync(
        @WebParam(name = "getYearlyMedianPricesChartURLRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getYearlyMedianPricesChartURLRequest")
        GetYearlyMedianPricesChartURLRequest getYearlyMedianPricesChartURLRequest);

    /**
     * 
     * @param getYearlyMedianPricesChartURLRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getYearlyMedianPricesChartURL")
    public Future<?> getYearlyMedianPricesChartURLAsync(
        @WebParam(name = "getYearlyMedianPricesChartURLRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getYearlyMedianPricesChartURLRequest")
        GetYearlyMedianPricesChartURLRequest getYearlyMedianPricesChartURLRequest,
        @WebParam(name = "getYearlyMedianPricesChartURLResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetYearlyMedianPricesChartURLResponse> asyncHandler);

    /**
     * 
     * @param getYearlyMedianPricesChartURLRequest
     * @return
     *     returns com.tooltwist.bsg.client.GetYearlyMedianPricesChartURLResponse
     */
    @WebMethod
    @WebResult(name = "getYearlyMedianPricesChartURLResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getYearlyMedianPricesChartURLResponse")
    public GetYearlyMedianPricesChartURLResponse getYearlyMedianPricesChartURL(
        @WebParam(name = "getYearlyMedianPricesChartURLRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getYearlyMedianPricesChartURLRequest")
        GetYearlyMedianPricesChartURLRequest getYearlyMedianPricesChartURLRequest);

    /**
     * 
     * @param getSalesByNumberRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.client.GetSalesByNumberResponse>
     */
    @WebMethod(operationName = "getSalesByNumber")
    public Response<GetSalesByNumberResponse> getSalesByNumberAsync(
        @WebParam(name = "getSalesByNumberRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSalesByNumberRequest")
        GetSalesByNumberRequest getSalesByNumberRequest);

    /**
     * 
     * @param asyncHandler
     * @param getSalesByNumberRequest
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getSalesByNumber")
    public Future<?> getSalesByNumberAsync(
        @WebParam(name = "getSalesByNumberRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSalesByNumberRequest")
        GetSalesByNumberRequest getSalesByNumberRequest,
        @WebParam(name = "getSalesByNumberResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetSalesByNumberResponse> asyncHandler);

    /**
     * 
     * @param getSalesByNumberRequest
     * @return
     *     returns com.tooltwist.bsg.client.GetSalesByNumberResponse
     */
    @WebMethod
    @WebResult(name = "getSalesByNumberResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSalesByNumberResponse")
    public GetSalesByNumberResponse getSalesByNumber(
        @WebParam(name = "getSalesByNumberRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSalesByNumberRequest")
        GetSalesByNumberRequest getSalesByNumberRequest);

    /**
     * 
     * @param getMonthlyMedianPricesChartURLRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.client.GetMonthlyMedianPricesChartURLResponse>
     */
    @WebMethod(operationName = "getMonthlyMedianPricesChartURL")
    public Response<GetMonthlyMedianPricesChartURLResponse> getMonthlyMedianPricesChartURLAsync(
        @WebParam(name = "getMonthlyMedianPricesChartURLRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getMonthlyMedianPricesChartURLRequest")
        GetMonthlyMedianPricesChartURLRequest getMonthlyMedianPricesChartURLRequest);

    /**
     * 
     * @param getMonthlyMedianPricesChartURLRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getMonthlyMedianPricesChartURL")
    public Future<?> getMonthlyMedianPricesChartURLAsync(
        @WebParam(name = "getMonthlyMedianPricesChartURLRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getMonthlyMedianPricesChartURLRequest")
        GetMonthlyMedianPricesChartURLRequest getMonthlyMedianPricesChartURLRequest,
        @WebParam(name = "getMonthlyMedianPricesChartURLResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetMonthlyMedianPricesChartURLResponse> asyncHandler);

    /**
     * 
     * @param getMonthlyMedianPricesChartURLRequest
     * @return
     *     returns com.tooltwist.bsg.client.GetMonthlyMedianPricesChartURLResponse
     */
    @WebMethod
    @WebResult(name = "getMonthlyMedianPricesChartURLResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getMonthlyMedianPricesChartURLResponse")
    public GetMonthlyMedianPricesChartURLResponse getMonthlyMedianPricesChartURL(
        @WebParam(name = "getMonthlyMedianPricesChartURLRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getMonthlyMedianPricesChartURLRequest")
        GetMonthlyMedianPricesChartURLRequest getMonthlyMedianPricesChartURLRequest);

    /**
     * 
     * @param getCapitalGrowthRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.client.GetCapitalGrowthResponse>
     */
    @WebMethod(operationName = "getCapitalGrowth")
    public Response<GetCapitalGrowthResponse> getCapitalGrowthAsync(
        @WebParam(name = "getCapitalGrowthRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getCapitalGrowthRequest")
        GetCapitalGrowthRequest getCapitalGrowthRequest);

    /**
     * 
     * @param getCapitalGrowthRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getCapitalGrowth")
    public Future<?> getCapitalGrowthAsync(
        @WebParam(name = "getCapitalGrowthRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getCapitalGrowthRequest")
        GetCapitalGrowthRequest getCapitalGrowthRequest,
        @WebParam(name = "getCapitalGrowthResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetCapitalGrowthResponse> asyncHandler);

    /**
     * 
     * @param getCapitalGrowthRequest
     * @return
     *     returns com.tooltwist.bsg.client.GetCapitalGrowthResponse
     */
    @WebMethod
    @WebResult(name = "getCapitalGrowthResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getCapitalGrowthResponse")
    public GetCapitalGrowthResponse getCapitalGrowth(
        @WebParam(name = "getCapitalGrowthRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getCapitalGrowthRequest")
        GetCapitalGrowthRequest getCapitalGrowthRequest);

    /**
     * 
     * @param getMonthlyMedianPricesRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.client.GetMonthlyMedianPricesResponse>
     */
    @WebMethod(operationName = "getMonthlyMedianPrices")
    public Response<GetMonthlyMedianPricesResponse> getMonthlyMedianPricesAsync(
        @WebParam(name = "getMonthlyMedianPricesRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getMonthlyMedianPricesRequest")
        GetMonthlyMedianPricesRequest getMonthlyMedianPricesRequest);

    /**
     * 
     * @param asyncHandler
     * @param getMonthlyMedianPricesRequest
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getMonthlyMedianPrices")
    public Future<?> getMonthlyMedianPricesAsync(
        @WebParam(name = "getMonthlyMedianPricesRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getMonthlyMedianPricesRequest")
        GetMonthlyMedianPricesRequest getMonthlyMedianPricesRequest,
        @WebParam(name = "getMonthlyMedianPricesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetMonthlyMedianPricesResponse> asyncHandler);

    /**
     * 
     * @param getMonthlyMedianPricesRequest
     * @return
     *     returns com.tooltwist.bsg.client.GetMonthlyMedianPricesResponse
     */
    @WebMethod
    @WebResult(name = "getMonthlyMedianPricesResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getMonthlyMedianPricesResponse")
    public GetMonthlyMedianPricesResponse getMonthlyMedianPrices(
        @WebParam(name = "getMonthlyMedianPricesRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getMonthlyMedianPricesRequest")
        GetMonthlyMedianPricesRequest getMonthlyMedianPricesRequest);

    /**
     * 
     * @param getSalesByPriceRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.client.GetSalesByPriceResponse>
     */
    @WebMethod(operationName = "getSalesByPrice")
    public Response<GetSalesByPriceResponse> getSalesByPriceAsync(
        @WebParam(name = "getSalesByPriceRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSalesByPriceRequest")
        GetSalesByPriceRequest getSalesByPriceRequest);

    /**
     * 
     * @param asyncHandler
     * @param getSalesByPriceRequest
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getSalesByPrice")
    public Future<?> getSalesByPriceAsync(
        @WebParam(name = "getSalesByPriceRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSalesByPriceRequest")
        GetSalesByPriceRequest getSalesByPriceRequest,
        @WebParam(name = "getSalesByPriceResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetSalesByPriceResponse> asyncHandler);

    /**
     * 
     * @param getSalesByPriceRequest
     * @return
     *     returns com.tooltwist.bsg.client.GetSalesByPriceResponse
     */
    @WebMethod
    @WebResult(name = "getSalesByPriceResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSalesByPriceResponse")
    public GetSalesByPriceResponse getSalesByPrice(
        @WebParam(name = "getSalesByPriceRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSalesByPriceRequest")
        GetSalesByPriceRequest getSalesByPriceRequest);

    /**
     * 
     * @param getSalesByNumberChartURLRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.client.GetSalesByNumberChartURLResponse>
     */
    @WebMethod(operationName = "getSalesByNumberChartURL")
    public Response<GetSalesByNumberChartURLResponse> getSalesByNumberChartURLAsync(
        @WebParam(name = "getSalesByNumberChartURLRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSalesByNumberChartURLRequest")
        GetSalesByNumberChartURLRequest getSalesByNumberChartURLRequest);

    /**
     * 
     * @param getSalesByNumberChartURLRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getSalesByNumberChartURL")
    public Future<?> getSalesByNumberChartURLAsync(
        @WebParam(name = "getSalesByNumberChartURLRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSalesByNumberChartURLRequest")
        GetSalesByNumberChartURLRequest getSalesByNumberChartURLRequest,
        @WebParam(name = "getSalesByNumberChartURLResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetSalesByNumberChartURLResponse> asyncHandler);

    /**
     * 
     * @param getSalesByNumberChartURLRequest
     * @return
     *     returns com.tooltwist.bsg.client.GetSalesByNumberChartURLResponse
     */
    @WebMethod
    @WebResult(name = "getSalesByNumberChartURLResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSalesByNumberChartURLResponse")
    public GetSalesByNumberChartURLResponse getSalesByNumberChartURL(
        @WebParam(name = "getSalesByNumberChartURLRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSalesByNumberChartURLRequest")
        GetSalesByNumberChartURLRequest getSalesByNumberChartURLRequest);

    /**
     * 
     * @param getSuburbStatisticsRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.client.GetSuburbStatisticsResponse>
     */
    @WebMethod(operationName = "getSuburbStatistics")
    public Response<GetSuburbStatisticsResponse> getSuburbStatisticsAsync(
        @WebParam(name = "getSuburbStatisticsRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSuburbStatisticsRequest")
        GetSuburbStatisticsRequest getSuburbStatisticsRequest);

    /**
     * 
     * @param asyncHandler
     * @param getSuburbStatisticsRequest
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getSuburbStatistics")
    public Future<?> getSuburbStatisticsAsync(
        @WebParam(name = "getSuburbStatisticsRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSuburbStatisticsRequest")
        GetSuburbStatisticsRequest getSuburbStatisticsRequest,
        @WebParam(name = "getSuburbStatisticsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetSuburbStatisticsResponse> asyncHandler);

    /**
     * 
     * @param getSuburbStatisticsRequest
     * @return
     *     returns com.tooltwist.bsg.client.GetSuburbStatisticsResponse
     */
    @WebMethod
    @WebResult(name = "getSuburbStatisticsResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSuburbStatisticsResponse")
    public GetSuburbStatisticsResponse getSuburbStatistics(
        @WebParam(name = "getSuburbStatisticsRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSuburbStatisticsRequest")
        GetSuburbStatisticsRequest getSuburbStatisticsRequest);

}
