
package com.tooltwist.bsg.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PropertyImageryServiceService", targetNamespace = "http://rpdata.com/bsg/schemas", wsdlLocation = "http://rpp.rpdata.com/bsgAU-2.0/ws/propertyImageryService.wsdl")
public class PropertyImageryServiceService
    extends Service
{

    private final static URL PROPERTYIMAGERYSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PROPERTYIMAGERYSERVICESERVICE_EXCEPTION;
    private final static QName PROPERTYIMAGERYSERVICESERVICE_QNAME = new QName("http://rpdata.com/bsg/schemas", "PropertyImageryServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://rpp.rpdata.com/bsgAU-2.0/ws/propertyImageryService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROPERTYIMAGERYSERVICESERVICE_WSDL_LOCATION = url;
        PROPERTYIMAGERYSERVICESERVICE_EXCEPTION = e;
    }

    public PropertyImageryServiceService() {
        super(__getWsdlLocation(), PROPERTYIMAGERYSERVICESERVICE_QNAME);
    }

    public PropertyImageryServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROPERTYIMAGERYSERVICESERVICE_QNAME, features);
    }

    public PropertyImageryServiceService(URL wsdlLocation) {
        super(wsdlLocation, PROPERTYIMAGERYSERVICESERVICE_QNAME);
    }

    public PropertyImageryServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROPERTYIMAGERYSERVICESERVICE_QNAME, features);
    }

    public PropertyImageryServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PropertyImageryServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PropertyImageryService
     */
    @WebEndpoint(name = "PropertyImageryServiceSoap11")
    public PropertyImageryService getPropertyImageryServiceSoap11() {
        return super.getPort(new QName("http://rpdata.com/bsg/schemas", "PropertyImageryServiceSoap11"), PropertyImageryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PropertyImageryService
     */
    @WebEndpoint(name = "PropertyImageryServiceSoap11")
    public PropertyImageryService getPropertyImageryServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://rpdata.com/bsg/schemas", "PropertyImageryServiceSoap11"), PropertyImageryService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROPERTYIMAGERYSERVICESERVICE_EXCEPTION!= null) {
            throw PROPERTYIMAGERYSERVICESERVICE_EXCEPTION;
        }
        return PROPERTYIMAGERYSERVICESERVICE_WSDL_LOCATION;
    }

}
