
package com.tooltwist.bsg.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "propertySearchServiceService", targetNamespace = "http://rpdata.com/bsg/schemas", wsdlLocation = "http://rpp.rpdata.com/bsgAU-2.0/ws/propertySearchService.wsdl")
public class PropertySearchServiceService
    extends Service
{

    private final static URL PROPERTYSEARCHSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PROPERTYSEARCHSERVICESERVICE_EXCEPTION;
    private final static QName PROPERTYSEARCHSERVICESERVICE_QNAME = new QName("http://rpdata.com/bsg/schemas", "propertySearchServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://rpp.rpdata.com/bsgAU-2.0/ws/propertySearchService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROPERTYSEARCHSERVICESERVICE_WSDL_LOCATION = url;
        PROPERTYSEARCHSERVICESERVICE_EXCEPTION = e;
    }

    public PropertySearchServiceService() {
        super(__getWsdlLocation(), PROPERTYSEARCHSERVICESERVICE_QNAME);
    }

    public PropertySearchServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROPERTYSEARCHSERVICESERVICE_QNAME, features);
    }

    public PropertySearchServiceService(URL wsdlLocation) {
        super(wsdlLocation, PROPERTYSEARCHSERVICESERVICE_QNAME);
    }

    public PropertySearchServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROPERTYSEARCHSERVICESERVICE_QNAME, features);
    }

    public PropertySearchServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PropertySearchServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PropertySearchService
     */
    @WebEndpoint(name = "propertySearchServiceSoap11")
    public PropertySearchService getPropertySearchServiceSoap11() {
        return super.getPort(new QName("http://rpdata.com/bsg/schemas", "propertySearchServiceSoap11"), PropertySearchService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PropertySearchService
     */
    @WebEndpoint(name = "propertySearchServiceSoap11")
    public PropertySearchService getPropertySearchServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://rpdata.com/bsg/schemas", "propertySearchServiceSoap11"), PropertySearchService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROPERTYSEARCHSERVICESERVICE_EXCEPTION!= null) {
            throw PROPERTYSEARCHSERVICESERVICE_EXCEPTION;
        }
        return PROPERTYSEARCHSERVICESERVICE_WSDL_LOCATION;
    }

}
