
package com.tooltwist.bsg.client;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SalesService", targetNamespace = "http://rpdata.com/bsg/schemas")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SalesService {


    /**
     * 
     * @param isHotSpotRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.client.IsHotSpotResponse>
     */
    @WebMethod(operationName = "isHotSpot")
    public Response<IsHotSpotResponse> isHotSpotAsync(
        @WebParam(name = "isHotSpotRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "isHotSpotRequest")
        IsHotSpotRequest isHotSpotRequest);

    /**
     * 
     * @param asyncHandler
     * @param isHotSpotRequest
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "isHotSpot")
    public Future<?> isHotSpotAsync(
        @WebParam(name = "isHotSpotRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "isHotSpotRequest")
        IsHotSpotRequest isHotSpotRequest,
        @WebParam(name = "isHotSpotResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<IsHotSpotResponse> asyncHandler);

    /**
     * 
     * @param isHotSpotRequest
     * @return
     *     returns com.tooltwist.bsg.client.IsHotSpotResponse
     */
    @WebMethod
    @WebResult(name = "isHotSpotResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "isHotSpotResponse")
    public IsHotSpotResponse isHotSpot(
        @WebParam(name = "isHotSpotRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "isHotSpotRequest")
        IsHotSpotRequest isHotSpotRequest);

    /**
     * 
     * @param getSalesPropertyIdsForAreaRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.client.GetSalesPropertyIdsForAreaResponse>
     */
    @WebMethod(operationName = "getSalesPropertyIdsForArea")
    public Response<GetSalesPropertyIdsForAreaResponse> getSalesPropertyIdsForAreaAsync(
        @WebParam(name = "getSalesPropertyIdsForAreaRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSalesPropertyIdsForAreaRequest")
        GetSalesPropertyIdsForAreaRequest getSalesPropertyIdsForAreaRequest);

    /**
     * 
     * @param getSalesPropertyIdsForAreaRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getSalesPropertyIdsForArea")
    public Future<?> getSalesPropertyIdsForAreaAsync(
        @WebParam(name = "getSalesPropertyIdsForAreaRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSalesPropertyIdsForAreaRequest")
        GetSalesPropertyIdsForAreaRequest getSalesPropertyIdsForAreaRequest,
        @WebParam(name = "getSalesPropertyIdsForAreaResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetSalesPropertyIdsForAreaResponse> asyncHandler);

    /**
     * 
     * @param getSalesPropertyIdsForAreaRequest
     * @return
     *     returns com.tooltwist.bsg.client.GetSalesPropertyIdsForAreaResponse
     */
    @WebMethod
    @WebResult(name = "getSalesPropertyIdsForAreaResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSalesPropertyIdsForAreaResponse")
    public GetSalesPropertyIdsForAreaResponse getSalesPropertyIdsForArea(
        @WebParam(name = "getSalesPropertyIdsForAreaRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSalesPropertyIdsForAreaRequest")
        GetSalesPropertyIdsForAreaRequest getSalesPropertyIdsForAreaRequest);

    /**
     * 
     * @param getSalesPropertySummaryListRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.client.GetSalesPropertySummaryListResponse>
     */
    @WebMethod(operationName = "getSalesPropertySummaryList")
    public Response<GetSalesPropertySummaryListResponse> getSalesPropertySummaryListAsync(
        @WebParam(name = "getSalesPropertySummaryListRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSalesPropertySummaryListRequest")
        GetSalesPropertySummaryListRequest getSalesPropertySummaryListRequest);

    /**
     * 
     * @param getSalesPropertySummaryListRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getSalesPropertySummaryList")
    public Future<?> getSalesPropertySummaryListAsync(
        @WebParam(name = "getSalesPropertySummaryListRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSalesPropertySummaryListRequest")
        GetSalesPropertySummaryListRequest getSalesPropertySummaryListRequest,
        @WebParam(name = "getSalesPropertySummaryListResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetSalesPropertySummaryListResponse> asyncHandler);

    /**
     * 
     * @param getSalesPropertySummaryListRequest
     * @return
     *     returns com.tooltwist.bsg.client.GetSalesPropertySummaryListResponse
     */
    @WebMethod
    @WebResult(name = "getSalesPropertySummaryListResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSalesPropertySummaryListResponse")
    public GetSalesPropertySummaryListResponse getSalesPropertySummaryList(
        @WebParam(name = "getSalesPropertySummaryListRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSalesPropertySummaryListRequest")
        GetSalesPropertySummaryListRequest getSalesPropertySummaryListRequest);

    /**
     * 
     * @param getSalesPropertyIdsByRadiusRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.client.GetSalesPropertyIdsByRadiusResponse>
     */
    @WebMethod(operationName = "getSalesPropertyIdsByRadius")
    public Response<GetSalesPropertyIdsByRadiusResponse> getSalesPropertyIdsByRadiusAsync(
        @WebParam(name = "getSalesPropertyIdsByRadiusRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSalesPropertyIdsByRadiusRequest")
        GetSalesPropertyIdsByRadiusRequest getSalesPropertyIdsByRadiusRequest);

    /**
     * 
     * @param getSalesPropertyIdsByRadiusRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getSalesPropertyIdsByRadius")
    public Future<?> getSalesPropertyIdsByRadiusAsync(
        @WebParam(name = "getSalesPropertyIdsByRadiusRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSalesPropertyIdsByRadiusRequest")
        GetSalesPropertyIdsByRadiusRequest getSalesPropertyIdsByRadiusRequest,
        @WebParam(name = "getSalesPropertyIdsByRadiusResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetSalesPropertyIdsByRadiusResponse> asyncHandler);

    /**
     * 
     * @param getSalesPropertyIdsByRadiusRequest
     * @return
     *     returns com.tooltwist.bsg.client.GetSalesPropertyIdsByRadiusResponse
     */
    @WebMethod
    @WebResult(name = "getSalesPropertyIdsByRadiusResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSalesPropertyIdsByRadiusResponse")
    public GetSalesPropertyIdsByRadiusResponse getSalesPropertyIdsByRadius(
        @WebParam(name = "getSalesPropertyIdsByRadiusRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSalesPropertyIdsByRadiusRequest")
        GetSalesPropertyIdsByRadiusRequest getSalesPropertyIdsByRadiusRequest);

    /**
     * 
     * @param getSaleDetailRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.client.GetSaleDetailResponse>
     */
    @WebMethod(operationName = "getSaleDetail")
    public Response<GetSaleDetailResponse> getSaleDetailAsync(
        @WebParam(name = "getSaleDetailRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSaleDetailRequest")
        GetSaleDetailRequest getSaleDetailRequest);

    /**
     * 
     * @param getSaleDetailRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getSaleDetail")
    public Future<?> getSaleDetailAsync(
        @WebParam(name = "getSaleDetailRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSaleDetailRequest")
        GetSaleDetailRequest getSaleDetailRequest,
        @WebParam(name = "getSaleDetailResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetSaleDetailResponse> asyncHandler);

    /**
     * 
     * @param getSaleDetailRequest
     * @return
     *     returns com.tooltwist.bsg.client.GetSaleDetailResponse
     */
    @WebMethod
    @WebResult(name = "getSaleDetailResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSaleDetailResponse")
    public GetSaleDetailResponse getSaleDetail(
        @WebParam(name = "getSaleDetailRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getSaleDetailRequest")
        GetSaleDetailRequest getSaleDetailRequest);

    /**
     * 
     * @param refineSoldPropertiesRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.client.RefineSoldPropertiesResponse>
     */
    @WebMethod(operationName = "refineSoldProperties")
    public Response<RefineSoldPropertiesResponse> refineSoldPropertiesAsync(
        @WebParam(name = "refineSoldPropertiesRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "refineSoldPropertiesRequest")
        RefineSoldPropertiesRequest refineSoldPropertiesRequest);

    /**
     * 
     * @param refineSoldPropertiesRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "refineSoldProperties")
    public Future<?> refineSoldPropertiesAsync(
        @WebParam(name = "refineSoldPropertiesRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "refineSoldPropertiesRequest")
        RefineSoldPropertiesRequest refineSoldPropertiesRequest,
        @WebParam(name = "refineSoldPropertiesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<RefineSoldPropertiesResponse> asyncHandler);

    /**
     * 
     * @param refineSoldPropertiesRequest
     * @return
     *     returns com.tooltwist.bsg.client.RefineSoldPropertiesResponse
     */
    @WebMethod
    @WebResult(name = "refineSoldPropertiesResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "refineSoldPropertiesResponse")
    public RefineSoldPropertiesResponse refineSoldProperties(
        @WebParam(name = "refineSoldPropertiesRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "refineSoldPropertiesRequest")
        RefineSoldPropertiesRequest refineSoldPropertiesRequest);

    /**
     * 
     * @param getHomeBuyerIndexRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.client.GetHomeBuyerIndexResponse>
     */
    @WebMethod(operationName = "getHomeBuyerIndex")
    public Response<GetHomeBuyerIndexResponse> getHomeBuyerIndexAsync(
        @WebParam(name = "getHomeBuyerIndexRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getHomeBuyerIndexRequest")
        GetHomeBuyerIndexRequest getHomeBuyerIndexRequest);

    /**
     * 
     * @param getHomeBuyerIndexRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getHomeBuyerIndex")
    public Future<?> getHomeBuyerIndexAsync(
        @WebParam(name = "getHomeBuyerIndexRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getHomeBuyerIndexRequest")
        GetHomeBuyerIndexRequest getHomeBuyerIndexRequest,
        @WebParam(name = "getHomeBuyerIndexResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetHomeBuyerIndexResponse> asyncHandler);

    /**
     * 
     * @param getHomeBuyerIndexRequest
     * @return
     *     returns com.tooltwist.bsg.client.GetHomeBuyerIndexResponse
     */
    @WebMethod
    @WebResult(name = "getHomeBuyerIndexResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getHomeBuyerIndexResponse")
    public GetHomeBuyerIndexResponse getHomeBuyerIndex(
        @WebParam(name = "getHomeBuyerIndexRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getHomeBuyerIndexRequest")
        GetHomeBuyerIndexRequest getHomeBuyerIndexRequest);

}
