
package com.tooltwist.bsg.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SessionServiceService", targetNamespace = "http://rpdata.com/bsg/schemas", wsdlLocation = "http://rpp.rpdata.com/bsgAU-2.0/ws/sessionService.wsdl")
public class SessionServiceService
    extends Service
{

    private final static URL SESSIONSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SESSIONSERVICESERVICE_EXCEPTION;
    private final static QName SESSIONSERVICESERVICE_QNAME = new QName("http://rpdata.com/bsg/schemas", "SessionServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://rpp.rpdata.com/bsgAU-2.0/ws/sessionService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SESSIONSERVICESERVICE_WSDL_LOCATION = url;
        SESSIONSERVICESERVICE_EXCEPTION = e;
    }

    public SessionServiceService() {
        super(__getWsdlLocation(), SESSIONSERVICESERVICE_QNAME);
    }

    public SessionServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SESSIONSERVICESERVICE_QNAME, features);
    }

    public SessionServiceService(URL wsdlLocation) {
        super(wsdlLocation, SESSIONSERVICESERVICE_QNAME);
    }

    public SessionServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SESSIONSERVICESERVICE_QNAME, features);
    }

    public SessionServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SessionServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SessionService
     */
    @WebEndpoint(name = "SessionServiceSoap11")
    public SessionService getSessionServiceSoap11() {
        return super.getPort(new QName("http://rpdata.com/bsg/schemas", "SessionServiceSoap11"), SessionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SessionService
     */
    @WebEndpoint(name = "SessionServiceSoap11")
    public SessionService getSessionServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://rpdata.com/bsg/schemas", "SessionServiceSoap11"), SessionService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SESSIONSERVICESERVICE_EXCEPTION!= null) {
            throw SESSIONSERVICESERVICE_EXCEPTION;
        }
        return SESSIONSERVICESERVICE_WSDL_LOCATION;
    }

}
