
package com.tooltwist.bsg.client;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserService", targetNamespace = "http://rpdata.com/bsg/schemas")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @param getCurrentListingsRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.client.GetCurrentListingsResponse>
     */
    @WebMethod(operationName = "getCurrentListings")
    public Response<GetCurrentListingsResponse> getCurrentListingsAsync(
        @WebParam(name = "getCurrentListingsRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getCurrentListingsRequest")
        GetCurrentListingsRequest getCurrentListingsRequest);

    /**
     * 
     * @param getCurrentListingsRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getCurrentListings")
    public Future<?> getCurrentListingsAsync(
        @WebParam(name = "getCurrentListingsRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getCurrentListingsRequest")
        GetCurrentListingsRequest getCurrentListingsRequest,
        @WebParam(name = "getCurrentListingsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetCurrentListingsResponse> asyncHandler);

    /**
     * 
     * @param getCurrentListingsRequest
     * @return
     *     returns com.tooltwist.bsg.client.GetCurrentListingsResponse
     */
    @WebMethod
    @WebResult(name = "getCurrentListingsResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getCurrentListingsResponse")
    public GetCurrentListingsResponse getCurrentListings(
        @WebParam(name = "getCurrentListingsRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getCurrentListingsRequest")
        GetCurrentListingsRequest getCurrentListingsRequest);

    /**
     * 
     * @param getAllUserDetailsRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.client.GetAllUserDetailsResponse>
     */
    @WebMethod(operationName = "getAllUserDetails")
    public Response<GetAllUserDetailsResponse> getAllUserDetailsAsync(
        @WebParam(name = "getAllUserDetailsRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getAllUserDetailsRequest")
        GetAllUserDetailsRequest getAllUserDetailsRequest);

    /**
     * 
     * @param getAllUserDetailsRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getAllUserDetails")
    public Future<?> getAllUserDetailsAsync(
        @WebParam(name = "getAllUserDetailsRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getAllUserDetailsRequest")
        GetAllUserDetailsRequest getAllUserDetailsRequest,
        @WebParam(name = "getAllUserDetailsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetAllUserDetailsResponse> asyncHandler);

    /**
     * 
     * @param getAllUserDetailsRequest
     * @return
     *     returns com.tooltwist.bsg.client.GetAllUserDetailsResponse
     */
    @WebMethod
    @WebResult(name = "getAllUserDetailsResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getAllUserDetailsResponse")
    public GetAllUserDetailsResponse getAllUserDetails(
        @WebParam(name = "getAllUserDetailsRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getAllUserDetailsRequest")
        GetAllUserDetailsRequest getAllUserDetailsRequest);

    /**
     * 
     * @param getUserDetailsRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.client.GetUserDetailsResponse>
     */
    @WebMethod(operationName = "getUserDetails")
    public Response<GetUserDetailsResponse> getUserDetailsAsync(
        @WebParam(name = "getUserDetailsRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getUserDetailsRequest")
        GetUserDetailsRequest getUserDetailsRequest);

    /**
     * 
     * @param getUserDetailsRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getUserDetails")
    public Future<?> getUserDetailsAsync(
        @WebParam(name = "getUserDetailsRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getUserDetailsRequest")
        GetUserDetailsRequest getUserDetailsRequest,
        @WebParam(name = "getUserDetailsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetUserDetailsResponse> asyncHandler);

    /**
     * 
     * @param getUserDetailsRequest
     * @return
     *     returns com.tooltwist.bsg.client.GetUserDetailsResponse
     */
    @WebMethod
    @WebResult(name = "getUserDetailsResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getUserDetailsResponse")
    public GetUserDetailsResponse getUserDetails(
        @WebParam(name = "getUserDetailsRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getUserDetailsRequest")
        GetUserDetailsRequest getUserDetailsRequest);

    /**
     * 
     * @param getRecentSalesRequest
     * @return
     *     returns javax.xml.ws.Response<com.tooltwist.bsg.client.GetRecentSalesResponse>
     */
    @WebMethod(operationName = "getRecentSales")
    public Response<GetRecentSalesResponse> getRecentSalesAsync(
        @WebParam(name = "getRecentSalesRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getRecentSalesRequest")
        GetRecentSalesRequest getRecentSalesRequest);

    /**
     * 
     * @param asyncHandler
     * @param getRecentSalesRequest
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getRecentSales")
    public Future<?> getRecentSalesAsync(
        @WebParam(name = "getRecentSalesRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getRecentSalesRequest")
        GetRecentSalesRequest getRecentSalesRequest,
        @WebParam(name = "getRecentSalesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetRecentSalesResponse> asyncHandler);

    /**
     * 
     * @param getRecentSalesRequest
     * @return
     *     returns com.tooltwist.bsg.client.GetRecentSalesResponse
     */
    @WebMethod
    @WebResult(name = "getRecentSalesResponse", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getRecentSalesResponse")
    public GetRecentSalesResponse getRecentSales(
        @WebParam(name = "getRecentSalesRequest", targetNamespace = "http://rpdata.com/bsg/schemas", partName = "getRecentSalesRequest")
        GetRecentSalesRequest getRecentSalesRequest);

}
